name: CI
on:
  push:

jobs:
  detect_release:
    name: detect new release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: playbook
      uses: dawidd6/action-ansible-playbook@v2.2.0
      with:
        playbook: check.yml

  gen:
    name: gen
    runs-on: ubuntu-latest
    outputs:
      strategy: ${{ steps.gen.outputs.strategy }}
    steps:
    - uses: actions/checkout@v2
    - id: gen
      name: gen
      run: python gen.py

  build:
    needs: gen
    strategy: ${{ fromJson(needs.gen.outputs.strategy) }}
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: debug
      run: "echo '${{ matrix.tags }}'"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.dockerfile }}
        platforms: linux/amd64,linux/arm/v7
        push: true
        tags: ${{ matrix.tags }}
        cache-to: type=registry,ref=darknao/dotclear:${{ matrix.cache }},mode=max
        cache-from: type=registry,ref=darknao/dotclear:${{ matrix.cache }}
